# Generated by Django 6.0.6 on 2026-06-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_category_id_alter_course_id_alter_lesson_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(default=1, help_text='Paste YouTube video link here'),
            preserve_default=False,
        ),
    ]
